### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by kimch0612** [lazinism/clip_downloader#1]
안녕하세요 두로님 시청자입니다
귀차니즘님께서 짜주신 프로그램덕분에 두로님의 클립을 전부 크롤링할 수 있었습니다. 감사합니다.
다만 이렇게 이슈를 남기게 된 것은 코드에 몇가지 수정할 사항이 있는 것 같아서입니다.
export한 data에서 NTFS에서 사용 불가능한 단어를 삭제하는 파트가 있지 않습니까?
그곳에 몇가지를 추가로 필터링해야 하는 단어가 있었습니다.
제가 추가한 단어는  (?, ？, ！, *, \n) 이것들입니다.
일본어 자판에서 쓸 수 있는 특수기호들 또한 윈도우에서 걸러내는 경우가 있더라고요.
그리고 '\n' 의 경우에는 제가 NAS의 우분투 환경에서 크롤링을 했었는데 뱉어내길래 넣었습니다.
윈도우에서도 똑같이 오류가 나는지는 잘 모르겠네요.
그리고 하나 두개씩 다운로드를 받을때는 오류가 나지 않았지만, 3만개가 넘는 파일들을 한번에 긁으니깐 코드가 한번씩 중간에 튕길때가 있더라고요.
저같은 경우에는 오류가 나면 5번까지는 다시 시도하고 그래도 오류가 나면 패스하는 방식으로 코드를 조금 손봐서 사용했습니다.
저와 같이 대량으로 한번에 다운로드 하는 사람들을 위해서 이부분도 개선해주시면 어떨까 하는 생각이 드네요.
다시 한 번 프로그램 만들어주신 것에 감사의 말씀 드리며 제가 손 본 코드는 아래에 첨부하겠습니다.
[https://chals.myqnapcloud.com/share.cgi?ssid=0ef6827d8f784ed9bdb342df6f8a2ae7](url)

**Comment by lazinism** [comment]
수정했습니다.
